import "dotenv/config";
import express from "express";
import cors from "cors";
import path from "path";
import { fileURLToPath } from "url";
import authRoutes from "./routes/auth.js";
import tourRoutes from "./routes/tours.js";
import bookingRoutes from "./routes/bookings.js";
import promoRoutes from "./routes/promos.js";
import reviewRoutes from "./routes/reviews.js";
import adminRoutes from "./routes/admin.js";

const app=express();
const __dirname=path.dirname(fileURLToPath(import.meta.url));
app.use(cors({origin:process.env.CLIENT_URL||"http://localhost:5173"}));
app.use(express.json({limit:"2mb"}));
app.use("/uploads",express.static(path.join(__dirname,"../uploads")));
app.get("/api/health",(req,res)=>res.json({status:"ok",service:"tourium-api"}));
app.use("/api/auth",authRoutes);
app.use("/api/tours",tourRoutes);
app.use("/api/bookings",bookingRoutes);
app.use("/api/promos",promoRoutes);
app.use("/api/reviews",reviewRoutes);
app.use("/api/admin",adminRoutes);
app.use((req,res)=>res.status(404).json({message:"Route not found."}));
app.listen(process.env.PORT||5000,()=>console.log(`API running on ${process.env.PORT||5000}`));
