CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(120) NOT NULL,
  email VARCHAR(180) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  phone VARCHAR(40),
  role VARCHAR(20) NOT NULL DEFAULT 'customer',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS tours (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),title VARCHAR(180) NOT NULL,slug VARCHAR(200) UNIQUE NOT NULL,destination VARCHAR(150) NOT NULL,short_description TEXT NOT NULL,description TEXT NOT NULL,duration_days INTEGER NOT NULL CHECK (duration_days > 0),price_lkr NUMERIC(12,2) NOT NULL CHECK (price_lkr >= 0),available_seats INTEGER NOT NULL DEFAULT 0 CHECK (available_seats >= 0),image_url TEXT,start_date DATE NOT NULL,end_date DATE NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'active',featured BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS itineraries (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tour_id UUID NOT NULL REFERENCES tours(id) ON DELETE CASCADE,day_number INTEGER NOT NULL,title VARCHAR(180) NOT NULL,description TEXT NOT NULL,meals VARCHAR(120),accommodation VARCHAR(180),UNIQUE(tour_id, day_number));
CREATE TABLE IF NOT EXISTS hotel_options (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tour_id UUID NOT NULL REFERENCES tours(id) ON DELETE CASCADE,name VARCHAR(180) NOT NULL,category VARCHAR(80),price_adjustment_lkr NUMERIC(12,2) NOT NULL DEFAULT 0,description TEXT);
CREATE TABLE IF NOT EXISTS vehicle_options (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tour_id UUID NOT NULL REFERENCES tours(id) ON DELETE CASCADE,name VARCHAR(180) NOT NULL,capacity INTEGER NOT NULL DEFAULT 1,price_adjustment_lkr NUMERIC(12,2) NOT NULL DEFAULT 0,description TEXT);
CREATE TABLE IF NOT EXISTS promo_codes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),code VARCHAR(40) UNIQUE NOT NULL,discount_type VARCHAR(20) NOT NULL CHECK (discount_type IN ('percent','fixed')),discount_value NUMERIC(12,2) NOT NULL CHECK (discount_value >= 0),valid_from DATE,valid_until DATE,max_uses INTEGER,use_count INTEGER NOT NULL DEFAULT 0,active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS bookings (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),booking_reference VARCHAR(30) UNIQUE NOT NULL,user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,tour_id UUID NOT NULL REFERENCES tours(id) ON DELETE RESTRICT,hotel_option_id UUID REFERENCES hotel_options(id) ON DELETE SET NULL,vehicle_option_id UUID REFERENCES vehicle_options(id) ON DELETE SET NULL,promo_code_id UUID REFERENCES promo_codes(id) ON DELETE SET NULL,travelers INTEGER NOT NULL CHECK (travelers > 0),subtotal_lkr NUMERIC(12,2) NOT NULL,discount_lkr NUMERIC(12,2) NOT NULL DEFAULT 0,total_amount_lkr NUMERIC(12,2) NOT NULL,booking_status VARCHAR(30) NOT NULL DEFAULT 'pending',payment_status VARCHAR(30) NOT NULL DEFAULT 'unpaid',special_request TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS payments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),booking_id UUID NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,provider VARCHAR(60) NOT NULL DEFAULT 'mock_gateway',transaction_reference VARCHAR(120),amount_lkr NUMERIC(12,2) NOT NULL,status VARCHAR(30) NOT NULL,paid_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS reviews (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,tour_id UUID NOT NULL REFERENCES tours(id) ON DELETE CASCADE,rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),comment TEXT NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id, tour_id));

INSERT INTO users (name,email,password_hash,role) VALUES ('Demo Admin','admin@demo.com',crypt('admin123',gen_salt('bf')),'admin'),('Demo Customer','customer@demo.com',crypt('customer123',gen_salt('bf')),'customer') ON CONFLICT (email) DO NOTHING;
INSERT INTO tours (title,slug,destination,short_description,description,duration_days,price_lkr,available_seats,image_url,start_date,end_date,featured) VALUES
('Ella Scenic Escape','ella-scenic-escape','Ella','Tea-country views, hikes, and iconic railway scenery.','Explore Nine Arches Bridge, Little Adam’s Peak, waterfalls, tea estates, and the peaceful hill-country atmosphere of Ella.',3,45000,18,'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1400&q=80',CURRENT_DATE+20,CURRENT_DATE+22,TRUE),
('Southern Coast Adventure','southern-coast-adventure','Galle & Mirissa','Historic Galle, beaches, ocean adventures, and local food.','Experience Galle Fort, coastal villages, Mirissa, whale-watching areas, seafood, and unforgettable sunsets.',4,68000,24,'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=1400&q=80',CURRENT_DATE+35,CURRENT_DATE+38,TRUE),
('Cultural Triangle Discovery','cultural-triangle-discovery','Sigiriya & Dambulla','Ancient cities, rock fortresses, temples, and village life.','Discover Sri Lanka’s cultural heritage through Sigiriya, Dambulla, village experiences, and historic landmarks.',3,52000,20,'https://images.unsplash.com/photo-1588258524675-c6198b6935a8?auto=format&fit=crop&w=1400&q=80',CURRENT_DATE+50,CURRENT_DATE+52,TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO itineraries(tour_id,day_number,title,description,meals,accommodation) SELECT id,1,'Arrival and Ella Town','Hotel check-in, town walk, and sunset viewpoint.','Dinner','Ella hotel' FROM tours WHERE slug='ella-scenic-escape' ON CONFLICT DO NOTHING;
INSERT INTO itineraries(tour_id,day_number,title,description,meals,accommodation) SELECT id,2,'Nine Arches and Little Adam’s Peak','Morning hike, bridge visit, tea experience, and leisure time.','Breakfast, Dinner','Ella hotel' FROM tours WHERE slug='ella-scenic-escape' ON CONFLICT DO NOTHING;
INSERT INTO itineraries(tour_id,day_number,title,description,meals,accommodation) SELECT id,3,'Waterfall and Departure','Visit a nearby waterfall and return journey.','Breakfast',NULL FROM tours WHERE slug='ella-scenic-escape' ON CONFLICT DO NOTHING;
INSERT INTO hotel_options(tour_id,name,category,price_adjustment_lkr,description) SELECT id,'Comfort Hotel','3 Star',0,'Comfortable double or twin room with breakfast.' FROM tours WHERE slug='ella-scenic-escape';
INSERT INTO hotel_options(tour_id,name,category,price_adjustment_lkr,description) SELECT id,'Boutique Mountain Resort','4 Star',18000,'Premium room with mountain views.' FROM tours WHERE slug='ella-scenic-escape';
INSERT INTO vehicle_options(tour_id,name,capacity,price_adjustment_lkr,description) SELECT id,'Shared Tourist Van',10,0,'Air-conditioned shared transport.' FROM tours WHERE slug='ella-scenic-escape';
INSERT INTO vehicle_options(tour_id,name,capacity,price_adjustment_lkr,description) SELECT id,'Private Car',3,25000,'Private air-conditioned car with driver.' FROM tours WHERE slug='ella-scenic-escape';
INSERT INTO promo_codes(code,discount_type,discount_value,valid_from,valid_until,max_uses) VALUES ('WELCOME10','percent',10,CURRENT_DATE,CURRENT_DATE+365,1000) ON CONFLICT (code) DO NOTHING;
